name: Integration Build and Test

on:
  workflow_call:
    inputs:
      integration_ref:
        required: false
        type: string
        default: ${{ github.sha }}
      integration_repo:
        required: false
        type: string
        default: ${{ github.repository }}
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
  workflow_dispatch:
    inputs:
      integration_ref:
        required: true
        type: string
      integration_repo:
        required: false
        type: string
        default: 'ros-navigation/navigation2'
      runs_on:
        required: true
        type: string

env:
  OVERLAY_WS: /opt/auto_ws

jobs:
  build_base_images:
    name: Build Base Images
    outputs:
      checkout_cache_key: ${{ steps.cache_source_checkout.outputs.checkout_cache_key }}
      metadata: ${{ steps.bake_base_stages.outputs.metadata }}
      overlay_cache_sha: ${{ steps.bake_base_stages.outputs.overlay_cache_sha }}
      overlay_ws: ${{ env.OVERLAY_WS }}
      tooler_image: ${{ steps.bake_base_stages.outputs.tooler_image }}
      validator_image: ${{ steps.bake_base_stages.outputs.validator_image }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout Integration Repo
        id: checkout_integration_repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.integration_ref }}
          repository: ${{ inputs.integration_repo }}
          token: ${{ secrets.GIT_CHECKOUT_PAT }}
          submodules: 'recursive'

      - name: Bake base stages
        id: bake_base_stages
        uses: ros-navigation/navigation2/.github/actions/bake-base-stages@main
        with:
          integration_repo: ${{ inputs.integration_repo }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache source checkout
        id: cache_source_checkout
        uses: ros-navigation/navigation2/.github/actions/cache-source-checkout@main
        with:
          integration_repo: ${{ inputs.integration_repo }}
          overlay_ws: ${{ env.OVERLAY_WS }}

  colcon_build_test:
    name: Colcon
    uses: ros-navigation/navigation2/.github/workflows/build_test_colcon.yaml@main
    secrets: inherit
    needs: build_base_images
    with:
      checkout_cache_key: ${{ needs.build_base_images.outputs.checkout_cache_key }}
      metadata: ${{ needs.build_base_images.outputs.metadata }}
      overlay_cache_sha: ${{ needs.build_base_images.outputs.overlay_cache_sha }}
      overlay_ws: ${{ needs.build_base_images.outputs.overlay_ws }}
      runs_on: ${{ inputs.runs_on }}
      tooler_image: ${{ needs.build_base_images.outputs.tooler_image }}
      validator_image: ${{ needs.build_base_images.outputs.validator_image }}

  build_prod_images:
    name: Prod
    uses: ros-navigation/navigation2/.github/workflows/build_prod_images.yaml@main
    secrets: inherit
    needs:
      - build_base_images
      - colcon_build_test
    with:
      cache_image: ${{ needs.build_base_images.outputs.tooler_image }}
      checkout_cache_key: ${{ needs.build_base_images.outputs.checkout_cache_key }}
      metadata: ${{ needs.build_base_images.outputs.metadata }}
      overlay_cache_key: ${{ needs.colcon_build_test.outputs.overlay_cache_key }}
      overlay_ws: ${{ needs.build_base_images.outputs.overlay_ws }}
      runs_on: ${{ inputs.runs_on }}
