name: Lint
on:
  pull_request:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ros-navigation/navigation2:main
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - name: Create python symlink
        run: |
          sudo ln -sf /usr/bin/python3 /usr/bin/python
      - uses: pre-commit/action@v3.0.1
