name: Lint
on:
  pull_request:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ros-navigation/navigation2:main
    steps:
      - uses: actions/checkout@v6
        with:
          path: ${{ env.path }}
      - uses: actions/setup-python@v6
      - name: Install pre-commit
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install pre-commit
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: |
          set -x
          source .venv/bin/activate
          source /opt/ros/rolling/setup.bash
          pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash
