name: Lint
on:
  pull_request:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ros-navigation/navigation2:main
    env:
        path: src/${{ github.repository }}
    steps:
      - uses: actions/checkout@v6
        with:
          path: ${{ env.path }}
      - name: Install pre-commit
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install pre-commit
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.path }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: |
          source .venv/bin/activate
          source /opt/ros/rolling/setup.bash
          cd ${{ env.path }}
          pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash
